### ISSUE TITLE
Indentation and curly bracket style

### ISSUE THREAD

**Issue by drewcassidy** [Voxelgon/Voxelgon#17]
I have been using always opening curly bracket on the same line, despite that being against the C# style guides.

C# style guides suggest using Allman style (opening brackets on next line, same indent). I just want to make sure all the code is written consistantly. After changing some sections of code to Allman style, I dont really know if i like it or not, but I'm open to using it

**Comment by WilliamBerryiii** [comment]
I prefer it, though it did take some time to make the transition from my java code.  That said, I don't use the style for my Powershell code so there is that too ... I can set up Resharper in visual studio to apply the formatting to the source files to keep it consistent.

**Comment by drewcassidy** [comment]
Alright, lets keep it how it is now then
