### ISSUE TITLE
Add a license file.

### ISSUE THREAD

**Issue by WilliamBerryiii** [Voxelgon/Voxelgon#22]
That's it.  Add a license file. MIT? Apache 2? Consider what Unity3d will allow too.

**Comment by drewcassidy** [comment]
It [doesnt look like](http://answers.unity3d.com/questions/13361/can-a-unity-project-be-open-sourced.html) unity has any limits on licensing projects.

I like the GPL license for this, since it requires anyone modifying it to also disclose their source

**Comment by WilliamBerryiii** [comment]
I might go for MIT or APache 2 since they are more liberal and encourage participation.  http://programmers.stackexchange.com/questions/56927/what-are-the-real-life-implications-for-an-apache-2-license

**Comment by drewcassidy** [comment]
Alright, after comparing them I think i'll swap it out for the Apache2 license

I've been looking at [this](http://choosealicense.com/licenses/).

**Comment by drewcassidy** [comment]
Do you think we should add copyrights to source files like it suggests?
